executor: slurm
jobs: 300
local-cores: 4
cores: 32
resources:
  # LDlink does not allow concurrent API calls
  - ldlink_calls=1
  - gnomad_api_calls=1
default-resources:
  runtime: 5
  mem_mb: threads * 3420
  slurm_account: "mrc-bsu-sl3-cpu"
  slurm_partition: cclake
#  tmpdir: "'/home/tw395/tmp'"
group-components:
  - coloc=4
  - gwas=4
software-deployment-method: "apptainer"
software-deployment-method: "conda"
scheduler: greedy
rerun-incomplete: True
rerun-triggers: "mtime"
notemp: False
keep-going: True
nolock: True
